import { Inter } from "next/font/google";
import 'bootstrap/dist/css/bootstrap.min.css';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
import BootstrapClient from "./components/BootstrapClient";
import Header from "./components/Header";
import Footer from "./components/Footer";
export const metadata = {
  title: "API DummyJson",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
     <body className={`bg-fondo text-white-50 ${inter.className}`}>
      <Header />
      <main>
        {children}
        </main>
      <Footer />
      <BootstrapClient/>
      </body>
    </html>
  );
}
